# Generated by Django 6.0 on 2026-01-12 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engins', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutCamionEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatutRadarEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Statut Radar',
                'verbose_name_plural': 'Statuts Radar',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_radar', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date_generation', models.DateField(auto_now_add=True)),
                ('duree_validite_mois', models.PositiveIntegerField(choices=[(3, '3 mois'), (4, '4 mois'), (6, '6 mois'), (12, '1 an')], default=6, verbose_name='Durée de validité')),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='radars/')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='radar', to='engins.inspectionengin', verbose_name='Inspection associée')),
                ('responsable_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.employe', verbose_name='Responsable génération')),
            ],
            options={
                'verbose_name': 'Radar',
                'verbose_name_plural': 'Radars',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='EvenementEngin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('code_evenement', models.CharField(editable=False, max_length=20, unique=True)),
                ('flotte_initiale', models.CharField(max_length=50)),
                ('flotte_beneficiaire', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('duree_jours', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('definitif', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, null=True)),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='engins.engin')),
                ('responsable_saisie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements_saisis', to='personnel.employe')),
                ('valideur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements_valides', to='personnel.employe')),
                ('statut_camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engins.statutcamionevenement')),
                ('statut_radar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='engins.statutradarevenement')),
                ('type_evenement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engins.typeevenement')),
            ],
            options={
                'verbose_name': 'Événement Engin',
                'verbose_name_plural': 'Événements Engins',
                'ordering': ['-date_debut'],
            },
        ),
    ]
