# Generated by Django 6.0 on 2026-02-27 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engins', '0002_statutcamionevenement_statutradarevenement_and_more'),
        ('flotte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assuranceengin',
            name='statut',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], default='VALIDE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='controletechnique',
            name='statut',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], default='VALIDE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='vignetteconformite',
            name='statut',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], default='VALIDE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='evenementengin',
            name='flotte_beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evenements_beneficiaires', to='flotte.flotte'),
        ),
        migrations.AlterField(
            model_name='evenementengin',
            name='flotte_initiale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements_initiaux', to='flotte.flotte'),
        ),
        migrations.CreateModel(
            name='CertificatJaugeage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('numero_certificat', models.CharField(max_length=100, unique=True, verbose_name='Numéro du certificat')),
                ('date_jaugeage', models.DateField(verbose_name='Date de jaugeage')),
                ('validite_mois', models.PositiveIntegerField(default=12, verbose_name='Validité (mois)')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('organisme', models.CharField(blank=True, max_length=150, null=True, verbose_name='Organisme certificateur')),
                ('observations', models.TextField(blank=True, null=True)),
                ('en_validite', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'Valide'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], default='VALIDE', max_length=20, verbose_name='Statut')),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats_jaugeage', to='engins.engin', verbose_name='Engin')),
            ],
            options={
                'verbose_name': 'Certificat de jaugeage',
                'verbose_name_plural': 'Certificats de jaugeage',
                'ordering': ['-date_expiration'],
                'indexes': [models.Index(fields=['date_expiration'], name='engins_cert_date_ex_dce89b_idx')],
            },
        ),
    ]
