# Generated by Django 6.0 on 2026-02-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engins', '0003_assuranceengin_statut_controletechnique_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteGrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro Carte Grise')),
                ('date_delivrance', models.DateField(verbose_name='Date de délivrance')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('statut', models.CharField(choices=[('VALIDE', 'Valide'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], default='VALIDE', max_length=20, verbose_name='Statut')),
                ('citerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartes_grises', to='engins.citerne')),
                ('engin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartes_grises', to='engins.engin')),
                ('remorque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartes_grises', to='engins.remorque')),
            ],
            options={
                'verbose_name': 'Carte Grise',
                'verbose_name_plural': 'Cartes Grises',
                'ordering': ['-date_expiration'],
                'indexes': [models.Index(fields=['numero'], name='engins_cart_numero_eebab6_idx'), models.Index(fields=['date_expiration'], name='engins_cart_date_ex_5bc26e_idx')],
            },
        ),
    ]
