# Generated by Django 6.0 on 2026-02-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engins', '0004_cartegrise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engin',
            old_name='date_integration_ums',
            new_name='date_integration',
        ),
    ]
