# Generated by Django 6.0 on 2026-01-12 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('engins', '0001_initial'),
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LieuDechargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UniteProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionEngin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_chargement', models.DateTimeField()),
                ('date_heure_dechargement', models.DateTimeField(blank=True, null=True)),
                ('type_cam', models.CharField(max_length=50)),
                ('volume_m3', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume (m³)')),
                ('poids_brut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Poids brut (T)')),
                ('poids_vide', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Poids à vide (T)')),
                ('poids_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Poids net (T)')),
                ('objectif_mt_jour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Objectif MT / jour')),
                ('observations', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('bon_livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='commercial.bonlivraison')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='personnel.employe')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_crees', to=settings.AUTH_USER_MODEL)),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='engins.engin')),
                ('pit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.pit')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='engins.siteengin')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.shift')),
                ('transporteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.transporteur')),
                ('unite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.uniteproduction')),
            ],
            options={
                'verbose_name': 'Production Engin',
                'verbose_name_plural': 'Productions Engins',
                'ordering': ['-date_heure_chargement'],
            },
        ),
    ]
