# Generated by Django 6.0 on 2026-01-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flotte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('engins', models.ManyToManyField(blank=True, related_name='flottes', to='engins.engin')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engins.siteengin')),
            ],
            options={
                'verbose_name': 'Flotte',
                'verbose_name_plural': 'Flottes',
                'ordering': ['nom'],
            },
        ),
    ]
