# Generated by Django 6.0 on 2026-01-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('reference', models.CharField(blank=True, help_text='Référence unique du client (ex: CLI0001)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('contact_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_secondaire', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_fixe', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_tva', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° TVA')),
                ('numero_rc', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Registre Commerce')),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('distributeur', 'Distributeur')], default='particulier', max_length=50)),
                ('limite_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Limite de crédit')),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèce'), ('virement', 'Virement'), ('cheque', 'Chèque')], default='espece', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_derniere_commande', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
    ]
