# Generated by Django 6.0 on 2026-01-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('numero_fournisseur', models.CharField(max_length=50, unique=True)),
                ('nom_societe', models.CharField(max_length=150)),
                ('motif_creation', models.TextField(blank=True, null=True)),
                ('societe_concernee', models.CharField(blank=True, max_length=150, null=True)),
                ('forme_juridique', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('activite', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom_societe'],
                'indexes': [models.Index(fields=['nom_societe'], name='fournisseur_nom_soc_830eab_idx'), models.Index(fields=['numero_fournisseur'], name='fournisseur_numero__ebc287_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=150)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('type_contact', models.CharField(choices=[('commercial', 'Responsable Commercial'), ('comptabilite', 'Comptabilité'), ('commande', 'Contact Commande'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='fournisseurs.fournisseur')),
            ],
            options={
                'verbose_name': 'Contact Fournisseur',
                'verbose_name_plural': 'Contacts Fournisseur',
                'ordering': ['nom'],
            },
        ),
    ]
