# Generated by Django 6.0 on 2026-01-12 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('engins', '0001_initial'),
        ('flotte', '0001_initial'),
        ('parametrage', '0001_initial'),
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Type de Formation',
                'verbose_name_plural': 'Types de Formations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypePermis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('validite_par_defaut', models.PositiveIntegerField(default=365, help_text='Durée de validité par défaut en jours')),
            ],
            options={
                'verbose_name': 'Type de Permis',
                'verbose_name_plural': 'Types de Permis',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ComportementConduite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('date_evaluation', models.DateField()),
                ('type_evaluation', models.CharField(choices=[('Sécurité', 'Sécurité'), ('Conduite', 'Conduite'), ('Ponctualité', 'Ponctualité'), ('Discipline', 'Discipline'), ('Autre', 'Autre')], default='Conduite', max_length=50)),
                ('evaluation', models.TextField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('niveau', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Bon', 'Bon'), ('Moyen', 'Moyen'), ('Insuffisant', 'Insuffisant')], max_length=20, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validée', 'Validée'), ('Annulée', 'Annulée')], default='En attente', max_length=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('action_corrective', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comportements', to='personnel.employe')),
                ('evaluateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_faites', to='personnel.employe')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_responsable', to='personnel.employe')),
            ],
            options={
                'verbose_name': 'Comportement et Conduite',
                'verbose_name_plural': 'Comportements et Conduites',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueHabilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation')], max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Habilitation',
                'verbose_name_plural': 'Historiques Habilitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuiviPASSMine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('numero_pass', models.CharField(max_length=50, unique=True)),
                ('type_pass', models.CharField(choices=[('Personnel', 'Personnel'), ('Sous-traitant', 'Sous-traitant'), ('Visiteur', 'Visiteur')], default='Personnel', max_length=20)),
                ('date_emission', models.DateField()),
                ('date_expiration', models.DateField()),
                ('jours_avant_expiration', models.PositiveIntegerField(default=30)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Expiré', 'Expiré'), ('Suspendu', 'Suspendu'), ('Annulé', 'Annulé')], default='Actif', max_length=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_pass', to='personnel.employe')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_emis', to='personnel.employe')),
                ('site_emission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.site')),
            ],
            options={
                'verbose_name': 'Suivi PASS Mine',
                'verbose_name_plural': 'Suivi PASS Mines',
                'ordering': ['-date_expiration'],
            },
        ),
        migrations.CreateModel(
            name='FormationChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('motif_theme', models.CharField(max_length=255, verbose_name='Motif / Thème')),
                ('date_formation', models.DateField(verbose_name='Date de réalisation')),
                ('duree_jours', models.PositiveIntegerField(default=1)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('organisme', models.CharField(blank=True, max_length=150, null=True)),
                ('qualification_actuelle', models.CharField(choices=[('Chauffeur PL', 'Chauffeur PL'), ('Chauffeur VL', 'Chauffeur VL'), ('Chauffeur', 'Chauffeur')], max_length=50, verbose_name='Qualification actuelle')),
                ('note', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54)])),
                ('appreciation', models.CharField(choices=[('Insuffisant', 'Insuffisant'), ('Passable', 'Passable'), ('Bien', 'Bien'), ('Très bien', 'Très bien'), ('Excellent', 'Excellent')], max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nombre_formation', models.CharField(choices=[('1', '1ère Formation'), ('2', '2ème Formation'), ('3', '3ème Formation')], default='1', max_length=2)),
                ('validite', models.DateField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Planifiée', 'Planifiée'), ('En cours', 'En cours'), ('Complétée', 'Complétée'), ('Annulée', 'Annulée')], default='Planifiée', max_length=20)),
                ('jours_avant_expiration', models.PositiveIntegerField(default=30)),
                ('categorie_engin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engins.categorieengin', verbose_name="Catégorie d'engin")),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations_chauffeur', to='personnel.employe')),
                ('flotte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flotte.flotte')),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_donnees', to='personnel.employe', verbose_name='Formateur')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.service')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='parametrage.site', verbose_name='Site de formation')),
                ('type_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='habilitation.typeformation')),
            ],
            options={
                'verbose_name': 'Formation Chauffeur',
                'verbose_name_plural': 'Formations Chauffeurs',
                'ordering': ['-date_formation'],
            },
        ),
        migrations.CreateModel(
            name='PermisTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('date_emission', models.DateField()),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Expiré', 'Expiré'), ('Suspendu', 'Suspendu')], default='Actif', max_length=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permis_travail', to='personnel.employe')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permis_emis', to='personnel.employe')),
                ('site_emission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.site')),
                ('type_permis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permis', to='habilitation.typepermis')),
            ],
            options={
                'verbose_name': 'Permis de Travail',
                'verbose_name_plural': 'Permis de Travail',
                'ordering': ['-date_expiration'],
            },
        ),
    ]
