# Generated by Django 6.0 on 2026-01-12 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('engins', '0001_initial'),
        ('parametrage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='N° Commande')),
                ('date_commande', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('code_budgetaire', models.CharField(blank=True, max_length=50, null=True)),
                ('compte_analytique', models.CharField(blank=True, max_length=50, null=True)),
                ('montant_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant HT')),
                ('tva_taux', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='TVA (%) appliquée')),
                ('montant_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant TTC')),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_crees', to=settings.AUTH_USER_MODEL)),
                ('tva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commandes', to='parametrage.tva')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bon de Commande',
                'verbose_name_plural': 'Bons de Commande',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='BonCommandeLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unite', models.CharField(blank=True, max_length=50, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_ligne', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commercial.boncommande')),
            ],
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='N° BL')),
                ('date_livraison', models.DateField()),
                ('transporteur', models.CharField(blank=True, max_length=100, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_livraison', to='commercial.boncommande')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bl_crees', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_livraison', to='engins.siteengin')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bl_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bon de Livraison',
                'verbose_name_plural': 'Bons de Livraison',
                'ordering': ['-date_livraison'],
            },
        ),
        migrations.CreateModel(
            name='BonLivraisonLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unite', models.CharField(blank=True, max_length=50, null=True)),
                ('bon_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commercial.bonlivraison')),
            ],
        ),
    ]
